export const listOfTypes = ["All", "Permanent", "Contract", "Temporary"];

export const listOfDistances = [
  {value: 'Any', label: 'Any'},
  {value: 5, label: "up to 5 miles"},
  {value: 10, label:'up to 10 miles'},
  {value: 20, label:'up to 20 miles'},
  {value: 30, label:'up to 30 miles'},
  {value: 50, label:'up to 50 miles'}
];
export const listfOfSectors = [
  {label: "All sectors"},
  {label: "Accounting"},
  {label: "Admin"},
  {label: "Agriculture Fishing and Forestry"},
  {label: "Airport"},
  {label: "Automotive"},
  {label: "Banking"},
  {label: "Building Services / FM"},
  {label: "Building and Construction"},
  {label: "Cleaning"},
  {label: "Community Services"},
  {label: "Construction"},
  {label: "Consultancy"},
  {label: "Customer Service"},
  {label: "Design"},
  {label: "Downstream oil and gas"},
  {label: "Driving"},
  {label: "Education and Training"},
  {label: "Electricians &amp; Lightning Protection"},
  {label: "Electronics"},
  {label: "Engineering"},
  {label: "Estate Agent"},
  {label: "FMCG"},
  {label: "Factory"},
  {label: "Financial Services"},
  {label: "Graduates and Trainees"},
  {label: "HR"},
  {label: "Health and Safety"},
  {label: "Health and Social Care"},
  {label: "Hospitality"},
  {label: "IT"},
  {label: "Insurance"},
  {label: "Legal"},
  {label: "Leisure and Sport"},
  {label: "Life Sciences"},
  {label: "Logistics"},
  {label: "Maintenance"},
  {label: "Manufacturing"},
  {label: "Marketing"},
  {label: "Media"},
  {label: "New Media and Internet"},
  {label: "Not for Profit and Charities"},
  {label: "Nursing"},
  {label: "Oil and Gas"},
  {label: "Procurement"},
  {label: "Property and Housing"},
  {label: "Public Sector"},
  {label: "Recruitment"},
  {label: "Recruitment Consultancy"},
  {label: "Refrigeration / AC"},
  {label: "Retail"},
  {label: "Sales"},
  {label: "Science"},
  {label: "Trade"},
  {label: "Travel and Tourism"},
];
